# Generated by Django 2.2.6 on 2020-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1024)),
                ('textoReseña', models.TextField()),
                ('imagen', models.ImageField(max_length=256, upload_to='images')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('enlaceAlbum', models.CharField(max_length=256, null=True)),
                ('tipoActividad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdosEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fichero', models.FileField(upload_to='files')),
                ('text0', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosDeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.TextField()),
                ('horarioEspecial', models.TextField()),
                ('ubicacion', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=256, null=True)),
                ('twitter', models.CharField(max_length=256, null=True)),
                ('instagram', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuntaRectora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('NO', 'No'), ('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('VOCAL', 'Vocal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('enlace', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('contacto', models.CharField(max_length=100, null=True)),
                ('perfil', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('titulaciones', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleoTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofertaEmpleo', models.CharField(max_length=200)),
                ('titulacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RevistaIngenio',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(max_length=256, upload_to='images')),
                ('fichero', models.FileField(upload_to='files')),
                ('fecha', models.DateField()),
                ('tablaContenido', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISITA_TECNICA', 'Visita técnica'), ('VISITA_CULTURAL', 'Visita cultural'), ('CONFERENCIA', 'Conferencia'), ('EXPOSICION', 'Exposición'), ('PADEL', 'Pádel'), ('TENIS', 'Tenis'), ('GOLF', 'Golf'), ('SENDERISMO', 'Senderismo'), ('BICICLETA', 'Bicicleta'), ('REUNION_PROMOCION', 'Reunión de promoción'), ('CONCURSO', 'Concurso'), ('ENCUENTRO_ASOCIADOS', 'Encuentro de asociados'), ('CONCIERTO', 'Concierto'), ('ACTIVIDAD_FAMILIAR', 'Actividad familiar'), ('CURSO', 'Curso'), ('OTRA', 'Otra')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AEROESPACIAL', 'Ingeniería Aeroespacial'), ('CIVIL', 'Ingeniería Civil'), ('TECNOLOGIAS_INDUSTRIALES', 'Ingeniería de las Tecnologías Industriales'), ('QUIMICA', 'Ingeniería Química'), ('TELECOMUNICACION', 'Ingeniería de las Tecnologías de la Telecomunicación'), ('ELECTRONICA_ROBOTICA_MECATRONICA', 'Ingeniería Electrónica, Robótica y Mecatrónica'), ('ENERGIA', 'Ingeniería de la Energía'), ('ORGANIZACION_INDUSTRIAL', 'Ingeniería de Organización Industrial')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateField()),
                ('cuentaBancaria', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('direccionPostal', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=256)),
                ('tipo', models.CharField(choices=[('ASOCIADO', 'Asociado'), ('GESTOR', 'Gestor'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('titulacion', models.CharField(max_length=100)),
                ('promocion', models.CharField(max_length=11)),
                ('añoFinalizacion', models.CharField(max_length=4)),
                ('empresa', models.CharField(max_length=150)),
                ('comunicaciones', models.BooleanField()),
                ('juntaRectora', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dniUsuario', models.CharField(max_length=9)),
                ('actividad', models.CharField(max_length=50)),
            ],
        ),
    ]
