# Generated by Django 2.2.6 on 2020-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juntarectora',
            name='id',
        ),
        migrations.RemoveField(
            model_name='titulacion',
            name='id',
        ),
        migrations.AlterField(
            model_name='juntarectora',
            name='puesto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
