# Generated by Django 2.2.6 on 2020-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0002_auto_20200417_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoactividad',
            name='id',
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
