# Generated by Django 2.2.6 on 2020-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0004_auto_20200422_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revistaingenio',
            name='imagen',
            field=models.ImageField(max_length=256, null=True, upload_to='images'),
        ),
    ]
