# Generated by Django 2.2.6 on 2020-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0005_auto_20200422_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revistaingenio',
            name='imagen',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='tablaContenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
