# Generated by Django 2.2.6 on 2020-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0010_auto_20200428_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccionPostal',
            field=models.TextField(),
        ),
    ]
