# Generated by Django 2.2.6 on 2020-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0011_auto_20200428_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='enlaceAlbum',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace al album'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.CharField(max_length=5, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(max_length=256, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='textoReseña',
            field=models.TextField(verbose_name='Texto de reseña'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='acuerdosempresas',
            name='fichero',
            field=models.FileField(upload_to='files', verbose_name='Fichero'),
        ),
        migrations.AlterField(
            model_name='acuerdosempresas',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='acuerdosempresas',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='facebook',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='horario',
            field=models.TextField(verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='horarioEspecial',
            field=models.TextField(verbose_name='Horario especial'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='instagram',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='twitter',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='juntarectora',
            name='puesto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='enlace',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='perfil',
            field=models.CharField(max_length=100, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='titulaciones',
            field=models.CharField(max_length=24, verbose_name='Titulaciones'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='titulo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='fichero',
            field=models.FileField(upload_to='files', verbose_name='Fichero'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='imagen',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='revistaingenio',
            name='tablaContenido',
            field=models.TextField(blank=True, null=True, verbose_name='Tabla de contenidos'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Titulación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='añoFinalizacion',
            field=models.CharField(max_length=4, verbose_name='Año de finalización'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comunicaciones',
            field=models.BooleanField(verbose_name='Comunicaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=256, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuentaBancaria',
            field=models.CharField(max_length=24, verbose_name='Cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccionPostal',
            field=models.TextField(verbose_name='Dirección postal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='promocion',
            field=models.CharField(max_length=11, verbose_name='Promoción'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, verbose_name='Usuario'),
        ),
    ]
