# Generated by Django 2.2.6 on 2020-05-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0012_auto_20200503_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipoActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.TipoActividad', verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='ofertaempleotitulacion',
            name='ofertaEmpleo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.OfertaEmpleo', verbose_name='Oferta de empleo'),
        ),
        migrations.AlterField(
            model_name='ofertaempleotitulacion',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.Titulacion', verbose_name='Titulación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='juntaRectora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.JuntaRectora', verbose_name='Junta rectora'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.TipoUsuario', verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.Titulacion', verbose_name='Titulación'),
        ),
        migrations.AlterField(
            model_name='usuarioactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.Actividad', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='usuarioactividad',
            name='dniUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.Usuario', verbose_name='Dni'),
        ),
    ]
