# Generated by Django 2.2.6 on 2020-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0015_auto_20200505_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Fichero'),
        ),
    ]
