# Generated by Django 2.2.6 on 2020-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0017_auto_20200505_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fichero',
            field=models.FileField(null=True, upload_to='files', verbose_name='Fichero'),
        ),
    ]
