# Generated by Django 2.2.6 on 2020-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0018_auto_20200505_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fichero',
            field=models.FileField(upload_to='files', verbose_name='Fichero'),
        ),
    ]
