# Generated by Django 2.2.6 on 2020-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0020_auto_20200506_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fichero',
            field=models.FileField(blank=True, upload_to='files', verbose_name='Fichero'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='enlace',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Enlace'),
        ),
    ]
