# Generated by Django 2.2.6 on 2020-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0021_auto_20200506_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaSolicitudesFin',
            field=models.DateField(verbose_name='Fecha de fin de las solicitudes'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechaSolicitudesInicio',
            field=models.DateField(verbose_name='Fecha de inicio de las solicitudes'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='numeroPlazas',
            field=models.IntegerField(verbose_name='Número de plazas'),
        ),
    ]
