# Generated by Django 2.2.6 on 2020-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0022_auto_20200506_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Título'),
        ),
    ]
