# Generated by Django 2.2.6 on 2020-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0023_auto_20200506_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
