# Generated by Django 2.2.6 on 2020-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0024_auto_20200506_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='contacto',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='perfil',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Perfil'),
        ),
        migrations.RemoveField(
            model_name='ofertaempleo',
            name='titulaciones',
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='titulaciones',
            field=models.ManyToManyField(to='gestionBD.Titulacion', verbose_name='Titulaciones'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='titulo',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Título'),
        ),
    ]
