# Generated by Django 2.2.6 on 2020-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0025_auto_20200507_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Fichero'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='titulaciones',
            field=models.ManyToManyField(blank=True, null=True, to='gestionBD.Titulacion', verbose_name='Titulaciones'),
        ),
    ]
