# Generated by Django 2.2.6 on 2020-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0026_auto_20200507_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contacto'),
        ),
    ]
