# Generated by Django 2.2.6 on 2020-05-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0027_auto_20200507_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='titulaciones',
            field=models.ManyToManyField(blank=True, to='gestionBD.Titulacion', verbose_name='Titulaciones'),
        ),
    ]
