# Generated by Django 2.2.6 on 2020-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0029_auto_20200508_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdosempresas',
            name='nombre',
            field=models.CharField(max_length=1024, verbose_name='Nombre'),
        ),
    ]
