# Generated by Django 2.2.6 on 2020-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0030_auto_20200508_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdosempresas',
            name='id',
        ),
        migrations.AlterField(
            model_name='acuerdosempresas',
            name='nombre',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
    ]
