# Generated by Django 2.2.6 on 2020-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0031_auto_20200508_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Usuario'),
        ),
    ]
