# Generated by Django 2.2.6 on 2020-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0033_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(max_length=128, verbose_name='Salt'),
        ),
    ]
