# Generated by Django 2.2.6 on 2020-07-14 16:57

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0034_auto_20200620_2155'),
    ]

    operations = [
        UnaccentExtension()
    ]
