# Generated by Django 2.2.6 on 2020-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0035_auto_20200714_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de la actividad'),
        ),
    ]
