# Generated by Django 2.2.6 on 2020-10-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0037_auto_20200804_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salt',
        ),
    ]
