# Generated by Django 2.2.6 on 2020-11-04 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0038_delete_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='enlaceAlbum',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace al album'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='enlace',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
    ]
