# Generated by Django 2.2.6 on 2021-02-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0039_auto_20201104_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='acuerdosempresas',
            options={'verbose_name': 'Acuerdos con empresas', 'verbose_name_plural': 'Acuerdos com empresas'},
        ),
        migrations.AlterModelOptions(
            name='datosdecontacto',
            options={'verbose_name': 'Datos de contacto', 'verbose_name_plural': 'Datos de contacto'},
        ),
        migrations.AlterModelOptions(
            name='juntarectora',
            options={'verbose_name': 'Junta Rectora', 'verbose_name_plural': 'Junta Rectora'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='ofertaempleo',
            options={'verbose_name': 'Oferta de empleo', 'verbose_name_plural': 'Ofertas de empleo'},
        ),
        migrations.AlterModelOptions(
            name='ofertaempleotitulacion',
            options={'verbose_name': 'Ofertas de empleo titulación', 'verbose_name_plural': 'Ofertas de empleo titulaciones'},
        ),
        migrations.AlterModelOptions(
            name='revistaingenio',
            options={'verbose_name': 'Revista Ingenio', 'verbose_name_plural': 'Revistas Ingenio'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'Tipo de actividad', 'verbose_name_plural': 'Tipos de actividades'},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'verbose_name': 'Tipo de usuario', 'verbose_name_plural': 'Tipos de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='titulacion',
            options={'verbose_name': 'Titulación', 'verbose_name_plural': 'Titulaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarioactividad',
            options={'verbose_name': 'Usuario actividad', 'verbose_name_plural': 'Usuarios actividades'},
        ),
        migrations.RenameField(
            model_name='usuarioactividad',
            old_name='dniUsuario',
            new_name='usuario',
        ),
    ]
