# Generated by Django 2.2.6 on 2021-02-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0040_auto_20210225_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.Usuario', verbose_name='Usuario'),
        ),
    ]
