# Generated by Django 2.2.6 on 2021-03-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0041_auto_20210225_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acuerdosempresas',
            options={'verbose_name': 'Acuerdos con empresas', 'verbose_name_plural': 'Acuerdos con empresas'},
        ),
    ]
