# Generated by Django 2.2.6 on 2021-03-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0043_listaesperausuarioactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaesperausuarioactividad',
            options={'verbose_name': 'Lista de espera usuario actividad', 'verbose_name_plural': 'Lista de espera usuarios actividades'},
        ),
    ]
