# Generated by Django 2.2.6 on 2021-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0044_auto_20210323_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='añoFinalizacion',
            field=models.IntegerField(verbose_name='Año de finalización'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='promocion',
            field=models.IntegerField(verbose_name='Promoción'),
        ),
    ]
