# Generated by Django 2.2.6 on 2021-05-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0045_auto_20210503_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosdecontacto',
            options={'verbose_name': 'Datos de contacto', 'verbose_name_plural': 'Datos de contactos'},
        ),
    ]
