# Generated by Django 2.2.6 on 2021-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0046_auto_20210520_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revistaingenio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
