# Generated by Django 2.2.6 on 2021-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0047_auto_20210523_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('estado', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Estado de la actividad')),
            ],
            options={
                'verbose_name': 'Estado de la actividad',
                'verbose_name_plural': 'Estado de las actividades',
            },
        ),
    ]
