# Generated by Django 2.2.6 on 2021-06-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0048_estadoactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoactividad',
            options={'verbose_name': 'Estado de la actividad', 'verbose_name_plural': 'Estados de las actividades'},
        ),
    ]
