# Generated by Django 2.2.6 on 2021-06-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0049_auto_20210607_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estadoActividad',
            field=models.ForeignKey(default='Sin estado', on_delete=django.db.models.deletion.CASCADE, to='gestionBD.EstadoActividad', verbose_name='Estado de la actividad'),
            preserve_default=False,
        ),
    ]
