# Generated by Django 2.2.6 on 2021-06-15 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0051_acuerdosempresas_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdecontacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='telefono',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='datosdecontacto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
