# Generated by Django 2.2.6 on 2021-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0052_auto_20210615_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosdecontacto',
            name='ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
    ]
