# Generated by Django 2.2.6 on 2021-06-16 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0053_auto_20210615_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbunFotos',
            fields=[
                ('nombre', models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('enlace', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Álbum de fotos',
                'verbose_name_plural': 'Álbumes de fotos',
            },
        ),
        migrations.AlterField(
            model_name='actividad',
            name='enlaceAlbum',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace al álbum'),
        ),
    ]
