# Generated by Django 2.2.6 on 2021-06-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0054_auto_20210616_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbunFotos',
            new_name='AlbumFotos',
        ),
    ]
