# Generated by Django 2.2.6 on 2021-06-16 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0056_auto_20210616_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumfotos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
