# Generated by Django 2.2.6 on 2021-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0057_albumfotos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('titulo', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='noticia',
            unique_together={('titulo', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='ofertaempleo',
            unique_together={('titulo', 'fecha')},
        ),
    ]
